basePath: /api/v1
definitions:
  model.PasswordResetResponse:
    properties:
      date_created:
        type: string
      success:
        type: boolean
    type: object
  model.SignInResponse:
    properties:
      date_created:
        type: string
      name:
        type: string
      success:
        type: boolean
    type: object
  model.Test:
    properties:
      amount:
        type: integer
      change:
        type: number
      date_created:
        type: string
      id:
        type: string
      usd:
        type: integer
    type: object
info:
  contact: {}
  description: This service is responsible for login logic. Handles login events and
    account creation
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
  title: Login API
  version: "1.0"
paths:
  /create-account:
    post:
      consumes:
      - application/json
      description: Checks for a unique username and then registers the account in
        the database
      parameters:
      - description: username of the account
        in: query
        name: username
        required: true
        type: string
      - description: name of the user
        in: query
        name: name
        required: true
        type: string
      - description: hashed account password
        in: query
        name: password_hash
        required: true
        type: string
      - description: email of the user
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SignInResponse'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Creates account for the user
      tags:
      - Auth
  /password-change:
    post:
      consumes:
      - application/json
      description: Checks for a reset code match and then changes the password
      parameters:
      - description: new hashed account password
        in: query
        name: password_hash
        required: true
        type: string
      - description: email of the user
        in: query
        name: email
        required: true
        type: string
      - description: password reset code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.PasswordResetResponse'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Allows users to change their password with a valid reset code
      tags:
      - Auth
  /password-reset-email:
    post:
      consumes:
      - application/json
      description: Checks for database for email and then sends a reset code to the
        email
      parameters:
      - description: email of the user
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.PasswordResetResponse'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Password Reset for user
      tags:
      - Auth
  /signin:
    get:
      consumes:
      - application/json
      description: Checks for a matching username and password hash in the database
      parameters:
      - description: username of the account
        in: query
        name: username
        required: true
        type: string
      - description: hashed account password
        in: query
        name: password_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SignInResponse'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Checks if credentials are correct
      tags:
      - Auth
  /test-no-auth:
    get:
      consumes:
      - application/json
      description: Will ask the service to generate a test json and return it back
        to the requester
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Test'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Gets a test value from the service, sanity check
      tags:
      - Tests
swagger: "2.0"
